# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s8pjxu7G7o5WHHHxEibOoU6dT7zGOUhw
"""

num1 = 5
num2 = 5
sum = num1 + num2
print('The sum of {0} and {1} is {2}'.format(num1, num2, sum))

num1 = 5
num2 = 10
sum = num1 + num2
print('The sum of {0} and {1} is {2}'.format(num1, num2, sum))